export {SliderHomeComponent } from "./slider-home/slider-home.component";
export {MyTixsComponent } from "./my-tixs/my-tixs.component";
export { LoginComponent } from "./login/login.component";
export { PartnersComponent } from "./partners/partners.component";
export { AffiliatesComponent } from "./affiliates/affiliates.component";
export { AffiliateDetailComponent } from "./affiliate-detail/affiliate-detail.component";
export { PartnerDetailComponent } from "./partner-detail/partner-detail.component";
export { TixDetailComponent } from "./tix-detail/tix-detail.component";
export { SignupComponent } from "./signup/signup.component";
export { NewMemberComponent } from "./new-member/new-member.component";
export { ComingComponent } from "./coming/coming.component";
export { AlltixsComponent } from "./alltixs/alltixs.component";
export { PartnerComponent } from "./new-member/partner/partner.component";
export { AffiliateComponent } from "./new-member/affiliate/affiliate.component";
export { ProfileComponent } from "./profile/profile.component";
export { AddtixsComponent } from "./addtixs/addtixs.component";
export { BookingComponent } from "./booking/booking.component";
export { AlltixslistComponent } from "./alltixslist/alltixslist.component";
export { AlltixsleftComponent } from "./alltixsleft/alltixsleft.component";
